objects/Account.object
<CustomObject>
    <fields>
        <fullName>Business_Area__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Business Area</label>
        <referenceTo>Business_Area__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Customer Type</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Customer_Type__c.Business_Area__c</field>
                <operation>equals</operation>
                <valueField>$Source.Business_Area__c</valueField>
            </filterItems>
            <isOptional>true</isOptional>
        </lookupFilter>
        <referenceTo>Customer_Type__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case.object
<CustomObject>
    <fields>
        <fullName>Acknowledge_Complaint__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Acknowledge Complaint</description>
        <label>Acknowledge Complaint</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Batch_Number__c</fullName>
        <label>Batch Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Business_Area__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Business Area</label>
        <referenceTo>Business_Area__c</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CaseOwner__c</fullName>
        <formula>Owner:User.Username</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Case Owner</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CaseReasons_C__c</fullName>
        <label>Case Reason</label>
        <picklist>
            <controllingField>Product_Group_C__c</controllingField>
            <picklistValues>
                <fullName>Bow</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dimensioning/Elongation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dimensioning/fitting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dimensioning/Length</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dimensioning/Model</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dimensioning/Squareness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Gloss level</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Identification/Absence of inkjet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Identification/Inkjet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Identification/label</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Identification/Wrong inkjet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Letter of contents absent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material/</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material/ Tensile impact strenght </fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material/Adhesion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material/Hardness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material/Recipe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Material/Shrinkage</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No tape</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Package/Boxes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Package/contamination</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Package/damaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Package/Number</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Package/pallet</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Package/wrong</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Surface</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Surface/waviness</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tape wrong position</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Twisting</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Wrong application of foil</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Cost_Detail__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Cost Detail</description>
        <label>Cost Detail</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Customer_PO_Number__c</fullName>
        <label>Customer PO Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Ref__c</fullName>
        <label>Customer Ref</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Customer_Type__c</fullName>
        <label>Customer Type</label>
        <picklist>
            <picklistValues>
                <fullName>InterCompany</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer - Formal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Customer – Informal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Investigation_status__c</fullName>
        <label>Investigation status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting Customer Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Order_Number__c</fullName>
        <label>Order Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Our_Item__c</fullName>
        <label>Our Item</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Group_C__c</fullName>
        <label>Product Group</label>
        <picklist>
            <picklistValues>
                <fullName>Tear Tape</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Labels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Extrusion Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Filter Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Porous Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cartons</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Leaflets</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Foil</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inks</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchased Products</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Manufactured Cards</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Protection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electrical &amp; Fasteners</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Electronics</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tapes and POS</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Security Seals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Printer Solutions</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Access Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hose Protection</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hardware</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Product Type</label>
        <referenceTo>Product2</referenceTo>
        <relationshipLabel>Cases</relationshipLabel>
        <relationshipName>Cases</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>QueriedQty__c</fullName>
        <label>Queried Quantity</label>
        <precision>18</precision>
        <scale>5</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Respond_to_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Respond to Customer</description>
        <label>Respond to Customer</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UM__c</fullName>
        <label>Unit Of Measure</label>
        <picklist>
            <picklistValues>
                <fullName>Metres</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pieces</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reels</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Thousands</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Case_Task__c.object
<CustomObject>
    <fields>
        <fullName>CaseID__c</fullName>
        <label>Case</label>
        <referenceTo>Case</referenceTo>
        <relationshipLabel>Case Tasks</relationshipLabel>
        <relationshipName>Case_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <fields>
        <fullName>Investigated_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Investigated By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Case_Tasks1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting Customer Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed – Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed – Unjustified</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>UM__c</fullName>
        <formula>TEXT(CaseID__r.UM__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Unit Of Measure</label>
        <type>Text</type>
    </fields>
    <label>Case Task</label>
    <nameField>
        <displayFormat>C{000000000}</displayFormat>
        <label>Case Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Case Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Customer_Type__c.object
<CustomObject>
    <fields>
        <fullName>Business_Area__c</fullName>
        <label>Business Area</label>
        <referenceTo>Business_Area__c</referenceTo>
        <relationshipLabel>Customer Types</relationshipLabel>
        <relationshipName>Customer_Types</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Customer Type</label>
    <nameField>
        <label>Customer Type Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Types</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Parent_Category__c</fullName>
        <label>Parent Category</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Reporting_Attribute__c</fullName>
        <label>Reporting Attribute</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requires_Know_Your_Customer__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Requires Know Your Customer</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

classes/CasesWithTasks.cls
public class CasesWithTasks {
    
    //Case Id To Acess
    Id  CaseID;  
    Case CurrentCaseDetails;
    public List<Case_Task__c> CaseTasks {get; private set; }
    public Product2 Productname {get;private set;}
    public Date ReportRunDate { get { return Date.today(); }}
    public Case_Task__c InvestigationCaseTask {get; private set; }
    public User InvestigatedBy  {get; private set; }
    public User CaseOwner{get; private set; }
    public String AccountDetails{get;private set;}
    //To Get Access to StandardConroller
    private ApexPages.StandardController controller;
    public CasesWithTasks () {
        CaseID= ApexPages.CurrentPage().getParameters().get('id');
        Init();
    }
    
    
    
    public CasesWithTasks (ApexPages.StandardController c) {
        controller = c;
        CaseID= c.getRecord().id;
        CaseTasks = new List<Case_Task__c>();
        InvestigationCaseTask = new Case_Task__c();
        Init();
    } 
    
    
    private void Init()
    {
        GetCaseDetails(CaseID);
        GetCaseTaskDetails(CaseID);
        SetInvestigatedBy();    
        SetCaseOwner();
    }
    //Get CaseTasks For the Present Case
    
    void SetInvestigatedBy()
    {
        try{
            List<User> InvestUser  =  [Select Name from user where id in( Select Investigated_By__c 
                                                                         from Case_task__c where CaseId__c= :ApexPages.CurrentPage().getParameters().get('id')  and Investigated_By__c <> null) Limit 1 ];
            
            if(InvestUser<>null)
            {
                InvestigatedBy  =InvestUser[0]; 
            }
        }
        catch(Exception e) {
        }     
    }      
    
    void SetCaseOwner()
    {
        try{
            List<User> CaseOwners  =  [Select Name from user where id in( Select OwnerId 
                                                                         from Case where id= :ApexPages.CurrentPage().getParameters().get('id')  ) Limit 1 ];
            
            if(CaseOwners  <>null)
            {
                CaseOwner  =CaseOwners[0]; 
            }
        }
        catch(Exception e) {}
        
    }      
    
    void GetCaseDetails(id id) { 
        try{
            CurrentCaseDetails= [SELECT AccountId, Acknowledge_Complaint__c,Batch_Number__c,Business_Area__c,CaseNumber,CaseOwner__c,CaseReasons_C__c,ClosedDate,ContactId,Cost_Detail__c,CreatedById,CreatedDate,CurrencyIsoCode,Customer_PO_Number__c,Customer_Ref__c,Customer_Type__c,Description,Id,Investigation_status__c,IsClosed,IsDeleted,IsEscalated,
                                 LastModifiedById,LastModifiedDate,LastReferencedDate,LastViewedDate,Order_Number__c,Origin,Our_Item__c,OwnerId,ParentId,Priority,Product_Group_C__c,Product_Type__c,QueriedQty__c,Reason,RecordTypeId,Respond_to_Customer__c,Status,Subject,SuppliedCompany,SuppliedEmail,SuppliedName,SuppliedPhone,SystemModstamp,Type,UM__c FROM Case
                                 where id = :CaseID limit 1]; 
            if(CurrentCaseDetails.Product_Type__c<>null)
            {
                Productname =  [Select CreatedById,CreatedDate,CurrencyIsoCode,Description,Family,Id,IsActive,IsDeleted,LastModifiedById,LastModifiedDate,Name,Parent_Category__c,ProductCode,Reporting_Attribute__c,Requires_Know_Your_Customer__c,Sub_Category__c,SystemModstamp from Product2 where id = :CurrentCaseDetails.Product_Type__c limit 1];
             }
            Account acc=[Select Name from Account where id=:CurrentCaseDetails.AccountId limit 1]  ;
            AccountDetails= acc.name;
            System.debug(AccountDetails);
            AccountDetails=AccountDetails.Split('-',0)[0];
            System.debug(AccountDetails);
        }
        catch(Exception e) {
        }
        
    }
    
    void  GetCaseTaskDetails(id id)
    {
        try
        {
            CaseTasks= [Select  Actual_Faulty_Qty__c,AssignedTo__c,CaseID__c,Containment_Action__c,Corrective_Action__c,Cost_to_Replace_Material__c,Cost_to_return_Samples__c,CreatedById,CreatedDate,Credit_Note_Reference__c,CurrencyIsoCode,Date_Completed__c,Date_Required__c,Date_Started__c,Details__c,Id,Investigated_By__c,Investigation_Details__c,Invoice_Number__c,IsDeleted,LastActivityDate,LastModifiedById,LastModifiedDate,Name,Preventative_Action__c,Price_Cost__c,Product_Group__c,RecordTypeId,Responsible_Department__c,Responsible_Site__c,Responsible_Sites__c,Root_Couse__c,Samples_Returned__c,Status__c,SystemModstamp,Total_Cost__c,UM__c,Value_of_Credit__c
                        from Case_Task__c where CaseID__c = :CaseID and Investigated_By__c <>null ];
            if(CaseTasks<>null && CaseTasks.size()>0 )
            {
                InvestigationCaseTask =CaseTasks[0];
            }
        }
        catch(Exception e) {}
    }
    
    
    
    
}