objects/Account.object
<CustomObject>
    <fields>
        <fullName>Customer_Name__c</fullName>
        <label>Customer Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

objects/Call_Report_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Call_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Report</label>
        <referenceTo>Trip_Report__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Call_Reports_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Call Reports</relationshipLabel>
        <relationshipName>Call_Reports_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Report - Opportunity</label>
    <nameField>
        <displayFormat>CRO-{0000}</displayFormat>
        <label>Call Report - Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports - Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Contact Type</label>
        <picklist>
            <picklistValues>
                <fullName>Financial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Innovation</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accounts Payable</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Buyer/Expeditor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Design Engineer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Estimator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>General Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Maintenance</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Production/Operations Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proprietor/Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Purchasing Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quality</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sales</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Senior Finance</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used by Distribution to indicate who the main point of contact is at the company.</inlineHelpText>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Discussion_Points__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Current Business Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Business Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Action Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitive Intelligence</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Internal_use_only__c</fullName>
        <label>Internal use only</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Discussion Points</relationshipLabel>
        <relationshipName>Discussion_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No__c</fullName>
        <label>No</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Discussion Points</relationshipLabel>
        <relationshipName>Discussion_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Trip_Report__c</fullName>
        <label>Call Report</label>
        <referenceTo>Trip_Report__c</referenceTo>
        <relationshipLabel>Discussion Points</relationshipLabel>
        <relationshipName>Discussion_Points</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Discussion Points</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discussion Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Trip_Report__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Trip_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Contact_Type__c</fullName>
        <label>Call Type</label>
        <picklist>
            <picklistValues>
                <fullName>Phone</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Video</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visit</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Customer_name__c</fullName>
        <formula>IF(NOT(ISBLANK( Account__c)),  Account__r.Name, IF(NOT(ISBLANK( Lead__c)),  Lead__r.Company , &apos;&apos;))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Executive_Summary__c</fullName>
        <label>Executive Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Introduction__c</fullName>
        <label>Objective</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Trip_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Location_Details__c</fullName>
        <label>Location Details</label>
        <length>2000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <picklist>
            <picklistValues>
                <fullName>Contact Address</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ESSENTRA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Next_Meeting__c</fullName>
        <defaultValue>today()+180</defaultValue>
        <label>Next Meeting</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Trip_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Visit_Date__c</fullName>
        <label>Call Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>leadname__c</fullName>
        <formula>Lead__r.FirstName &amp;&apos; &apos; &amp; Lead__r.LastName</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>leadname</label>
        <type>Text</type>
    </fields>
    <label>Call Report</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Subject</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trip_Report_Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <formula>IF( TEXT(Contact_Selection__c) == &apos;User&apos;,  User__r.FirstName +&apos; &apos;+ User__r.LastName +&apos;, &apos; + $Organization.Name , IF(TEXT(Contact_Selection__c) == &apos;Lead&apos;, Lead__r.FirstName + &apos; &apos; + Lead__r.LastName + &apos;, &apos; + Lead__r.Company,  Contact__r.FirstName + &apos; &apos; + Contact__r.LastName + &apos;, &apos; +Contact__r.Account.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Selection__c</fullName>
        <label>Contact</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Trip_Report_Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Trip_Report_Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No__c</fullName>
        <label>No</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>CASE( Contact_Selection__c , &apos;Contact&apos;,  Contact__r.Title , &apos;User&apos;,  User__r.Title, &apos;Lead&apos;,  Lead__r.Title, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trip_Report__c</fullName>
        <label>Call Report</label>
        <referenceTo>Trip_Report__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Trip_Report_Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trip_Report_Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Trip Report Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/tripreportDetailsCtrler.cls
public class tripreportDetailsCtrler 
{
    public Id tripReportId {get;set;}
    private List<Trip_Report__c> TripRep;
    private List<Trip_Report_Contact_Role__c> TripRepConRoles ;
    private List<Discussion_Points__c> TripRepPoints;
    private List<Call_Report_Opportunity__c> TripRepOppys;
    
    public tripreportDetailsCtrler ()
    {
        TripRep = new List<Trip_Report__c> ();
        TripRepConRoles = new List<Trip_Report_Contact_Role__c>();
        TripRepPoints = new List<Discussion_Points__c>();
        TripRepOppys = new List<Call_Report_Opportunity__c>();
        system.debug('\n'+tripReportId+'\n');
    }
    
    public Trip_Report__c getTripRep()
    {
        TripRep = [SELECT Name , Customer_name__c, leadname__c, Contact_Type__c, Location__c, Location_Details__c, Account__r.name, Opportunity__r.name, Visit_Date__c, Next_Meeting__c, Executive_Summary__c, Introduction__c FROM Trip_Report__c WHERE Id = :tripReportId LIMIT 1];
        if(TripRep.size() > 0)
            return TripRep[0];
        else
            return null;            
    }
    
    public List<Call_Report_Opportunity__c> getTripRepOppys()
    {
        TripRepOppys = [SELECT Id, Opportunity__c, Opportunity__r.name, Call_Report__c FROM Call_Report_Opportunity__c WHERE Call_Report__c = :tripReportId];
        return TripRepOppys;
    }
    
    public List<Trip_Report_Contact_Role__c> getTripRepConRoles()
    {
        TripRepConRoles = [SELECT Name, Title__c, Contact__c, Contact__r.Name, Contact_Selection__c, Lead__c, User__c, Contact_Name__c, Contact_Role__c, Primary_Contact__c, No__c FROM Trip_Report_Contact_Role__c WHERE Trip_Report__c = :tripReportId ORDER BY No__c];
        return TripRepConRoles;
    }
    public List<Discussion_Points__c> getTripRepPoints()
    {
        TripRepPoints = [SELECT Due_Date__c, Opportunity__c, Opportunity__r.name, Lead__c, Internal_use_only__c, No__c, Category__c, Responsible_contact__r.Name, Responsible_contact__c, Responsible_company__c, Responsible_selection__c, Responsible_user__r.Name, Responsible_user__c, Subject__c, internal_use__c, Summary__c, Trip_Report__c, Name FROM Discussion_Points__c WHERE Trip_Report__c = :tripReportId ORDER BY No__c];
        return TripRepPoints;
    }
    public List <Discussion_Points__c> getCurrentBusinessReview()
    {
        List<Discussion_Points__c> result = [SELECT Due_Date__c, Opportunity__c, Opportunity__r.name, Lead__c, Internal_use_only__c, No__c, Category__c, Responsible_contact__r.Name, Responsible_contact__c, Responsible_company__c, Responsible_selection__c, Responsible_user__r.Name, Responsible_user__c, Subject__c, internal_use__c, Summary__c, Trip_Report__c, Name FROM Discussion_Points__c WHERE Trip_Report__c = :tripReportId AND Category__c = 'Current Business Review' AND internal_use_only__c = 'No' ORDER BY No__c];       
        if(result.size() > 0)
            return result;
        else
            return null;
    }

    public List <Discussion_Points__c> getNewBusinessOpportunity()
    {
        List<Discussion_Points__c> result = [SELECT Due_Date__c, Opportunity__c, Opportunity__r.name, Lead__c, Internal_use_only__c, No__c, Category__c, Responsible_contact__r.Name, Responsible_contact__c, Responsible_company__c, Responsible_selection__c, Responsible_user__r.Name, Responsible_user__c, Subject__c, internal_use__c, Summary__c, Trip_Report__c, Name FROM Discussion_Points__c WHERE Trip_Report__c = :tripReportId AND Category__c = 'New Business Opportunity' AND internal_use_only__c = 'No' ORDER BY No__c];       
        if(result.size() > 0)
            return result;
        else
            return null;

    }

    public List <Discussion_Points__c> getCompetitiveIntelligence()
    {
        List<Discussion_Points__c> result = [SELECT Due_Date__c, Opportunity__c, Opportunity__r.name, Lead__c, Internal_use_only__c, No__c, Category__c, Responsible_contact__r.Name, Responsible_contact__c, Responsible_company__c, Responsible_selection__c, Responsible_user__r.Name, Responsible_user__c, Subject__c, internal_use__c, Summary__c, Trip_Report__c, Name FROM Discussion_Points__c WHERE Trip_Report__c = :tripReportId AND Category__c = 'Competitive Intelligence' AND internal_use_only__c = 'No' ORDER BY No__c];       
        if(result.size() > 0)
            return result;
        else
            return null;
    }

    public List <Discussion_Points__c> getMiscellaneous()
    {
        List<Discussion_Points__c> result = [SELECT Due_Date__c, Opportunity__c, Opportunity__r.name, Lead__c, Internal_use_only__c, No__c, Category__c, Responsible_contact__r.Name, Responsible_contact__c, Responsible_company__c, Responsible_selection__c, Responsible_user__r.Name, Responsible_user__c, Subject__c, internal_use__c, Summary__c, Trip_Report__c, Name FROM Discussion_Points__c WHERE Trip_Report__c = :tripReportId AND Category__c = 'Miscellaneous' AND internal_use_only__c = 'No' ORDER BY No__c];       
        if(result.size() > 0)
            return result;
        else
            return null;
    }

    public List <Discussion_Points__c> getActionItem()
    {
        List<Discussion_Points__c> result = [SELECT Due_Date__c, Opportunity__c, Opportunity__r.name, Lead__c, Internal_use_only__c, No__c, Category__c, Responsible_contact__r.Name, Responsible_contact__c, Responsible_company__c, Responsible_selection__c, Responsible_user__r.Name, Responsible_user__c, Subject__c, internal_use__c, Summary__c, Trip_Report__c, Name FROM Discussion_Points__c WHERE Trip_Report__c = :tripReportId AND Category__c = 'Action Item' AND internal_use_only__c = 'No' ORDER BY No__c];       
        if(result.size() > 0)
            return result;
        else
            return null;
    }
    public List <Discussion_Points__c> getNoCategory()
    {
        List<Discussion_Points__c> result = [SELECT Due_Date__c, Opportunity__c, Opportunity__r.name, Lead__c, Internal_use_only__c, No__c, Category__c, Responsible_contact__r.Name, Responsible_contact__c, Responsible_company__c, Responsible_selection__c, Responsible_user__r.Name, Responsible_user__c, Subject__c, internal_use__c, Summary__c, Trip_Report__c, Name FROM Discussion_Points__c WHERE Trip_Report__c = :tripReportId AND Category__c = '' AND internal_use_only__c = 'No' ORDER BY No__c];       
        if(result.size() > 0)
            return result;
        else
            return null;
    }
    
}