objects/Call_Report_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>Call_Report__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Report</label>
        <referenceTo>Trip_Report__c</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Call_Reports_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Call Reports</relationshipLabel>
        <relationshipName>Call_Reports_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Report - Opportunity</label>
    <nameField>
        <displayFormat>CRO-{0000}</displayFormat>
        <label>Call Report - Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports - Opportunities</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Used by Distribution to indicate who the main point of contact is at the company.</inlineHelpText>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Discussion_Points__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <picklist>
            <picklistValues>
                <fullName>Current Business Review</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Business Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Action Item</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Miscellaneous</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Competitive Intelligence</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Due_Date__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Internal_use_only__c</fullName>
        <label>Internal use only</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Discussion Points</relationshipLabel>
        <relationshipName>Discussion_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No__c</fullName>
        <label>No</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Discussion Points</relationshipLabel>
        <relationshipName>Discussion_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsible_company__c</fullName>
        <formula>IF( TEXT(Responsible_selection__c) == &apos;User&apos;,    Responsible_user__r.FirstName + &apos; &apos; +  Responsible_user__r.LastName +&apos;, &apos;+$Organization.Name , IF(TEXT(Responsible_selection__c) == &apos;Lead&apos;,   Lead__r.FirstName + &apos; &apos; +  Lead__r.LastName + &apos;, &apos; + Lead__r.Company,   Responsible_contact__r.FirstName + &apos; &apos; +  Responsible_contact__r.LastName + &apos;, &apos; +Responsible_contact__r.Account.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Responsible company</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Responsible_contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Discussion Points</relationshipLabel>
        <relationshipName>Discussion_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Responsible_selection__c</fullName>
        <label>Responsible</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Responsible_user__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Responsible</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Discussion_Points</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Trip_Report__c</fullName>
        <label>Call Report</label>
        <referenceTo>Trip_Report__c</referenceTo>
        <relationshipLabel>Discussion Points</relationshipLabel>
        <relationshipName>Discussion_Points</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>internal_use__c</fullName>
        <formula>IF(TEXT(Internal_use_only__c) == &apos;yes&apos;, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>internal use</label>
        <type>Checkbox</type>
    </fields>
    <label>Discussion Points</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Discussion Points</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Trip_Report__c.object
<CustomObject>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Trip_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>Trip_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Call Reports</relationshipLabel>
        <relationshipName>Call_Reports</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Call Report</label>
    <nameField>
        <displayFormat>CR-{0000}</displayFormat>
        <label>Subject</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Call Reports</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Trip_Report_Contact_Role__c.object
<CustomObject>
    <fields>
        <fullName>Contact_Name__c</fullName>
        <formula>IF( TEXT(Contact_Selection__c) == &apos;User&apos;,  User__r.FirstName +&apos; &apos;+ User__r.LastName +&apos;, &apos; + $Organization.Name , IF(TEXT(Contact_Selection__c) == &apos;Lead&apos;, Lead__r.FirstName + &apos; &apos; + Lead__r.LastName + &apos;, &apos; + Lead__r.Company,  Contact__r.FirstName + &apos; &apos; + Contact__r.LastName + &apos;, &apos; +Contact__r.Account.Name))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Contact Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Role__c</fullName>
        <label>Contact Role</label>
        <picklist>
            <picklistValues>
                <fullName>Business User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Economic Decision Maker</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Evaluator</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Executive Sponsor</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Influencer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Technical Buyer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact_Selection__c</fullName>
        <label>Contact</label>
        <picklist>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Trip_Report_Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lead__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Lead</label>
        <referenceTo>Lead</referenceTo>
        <relationshipName>Trip_Report_Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>No__c</fullName>
        <label>No</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Primary Contact</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <formula>CASE( Contact_Selection__c , &apos;Contact&apos;,  Contact__r.Title , &apos;User&apos;,  User__r.Title, &apos;Lead&apos;,  Lead__r.Title, &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Title</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trip_Report__c</fullName>
        <label>Call Report</label>
        <referenceTo>Trip_Report__c</referenceTo>
        <relationshipLabel>Participants</relationshipLabel>
        <relationshipName>Trip_Report_Contact_Roles</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Trip_Report_Contact_Roles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Participant</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Trip Report Contact Role Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Participants</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/ContactRoles_DiscussionPoints_Ctrler.cls
public with sharing class ContactRoles_DiscussionPoints_Ctrler 
{
    private final Trip_Report__c TripRep;
    public List<Trip_Report_Contact_Role__c> TripRepConRoles {get; set;}
    public List<Discussion_Points__c> TripRepPoints{get;set;}
    public List<Call_Report_Opportunity__c> Oppys{get;set;}
    public integer selectConRole {get; set;}
    public integer selectPoint{get; set;}
    
    public ContactRoles_DiscussionPoints_Ctrler (ApexPages.StandardController TripRepCtrler)
    {
        TripRep = (Trip_Report__c)TripRepCtrler.getRecord();
        TripRepConRoles = [SELECT Name, Title__c, Contact__c, Contact__r.Name, Contact_Selection__c, Lead__c, User__c, Contact_Name__c, Contact_Role__c, Primary_Contact__c, No__c FROM Trip_Report_Contact_Role__c WHERE Trip_Report__c = :TripRep.id ORDER BY No__c];
        TripRepPoints = [SELECT Id, Due_Date__c, Opportunity__c, Opportunity__r.name, Lead__c, Internal_use_only__c, No__c, Category__c, Responsible_contact__r.Name, Responsible_contact__c, Responsible_company__c, Responsible_selection__c, Responsible_user__r.Name, Responsible_user__c, Subject__c, internal_use__c, Summary__c, Trip_Report__c, Name FROM Discussion_Points__c WHERE Trip_Report__c = :TripRep.id ORDER BY No__c];
        Oppys = [SELECT Id, Opportunity__c, Opportunity__r.name, Call_Report__c FROM Call_Report_Opportunity__c WHERE Call_Report__c = :TripRep.id];
    }
    public void ConRoleAddRow()
    {
        decimal no = 0;
        if(TripRepConRoles.size() >= 1)
            no = TripRepConRoles[TripRepConRoles.size()-1].No__c+1;
        Trip_Report_Contact_Role__c newConRole = new Trip_Report_Contact_Role__c(Trip_Report__c = TripRep.id, No__c = no, Contact_Selection__c = 'Contact');
        TripRepConRoles.add(newConRole); 
    }
    public void ConRolesave()
    {
        try
        {
            for(Trip_Report_Contact_Role__c conRole : TripRepConRoles)
            {
                if(conRole.Primary_Contact__c == true && null != conRole.Contact__c)
                {
                    TripRep.Primary_Contact__c = conRole.Contact__c;
                    update TripRep;
                    break;
                }
            }
            upsert TripRepConRoles;
        }
        catch (Exception e)
        {
            system.debug('exception: '+e.getMessage());
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Following exception occurred: ' + e.getMessage()));
        } 
    }   
    
    public void ConRoleDelete()
    {
        system.debug(TripRepConRoles);
        if(TripRepConRoles.size() == 0)
            return;
        else
        {
            Trip_Report_Contact_Role__c toBeDeleted = null;
            integer i = 0;
            for(Trip_Report_Contact_Role__c tpc : TripRepConRoles)
            {
                if(tpc.No__c == selectConRole)
                {
                    if(tpc.id != null)
                        toBeDeleted = tpc;
                    TripRepConRoles.remove(i); 
                    system.debug(toBeDeleted);                  
                    break;
                }
                i++;
            }
            if(toBeDeleted != null)
            {
                Delete toBeDeleted;
            }
        }
    }
    
    public List <Discussion_Points__c> getNon_Internal_Discussion_Points()
    {
        List <Discussion_Points__c> non_internal = new List <Discussion_Points__c> (); 
        for(Discussion_Points__c dp : TripRepPoints)
        {
            if(dp.internal_use_only__c == 'No')
            {
                non_internal.add(dp);
            }
        }
        return non_internal;
    }   
    public List<Discussion_Points__c> getNoCategory()
    {
        List<Discussion_Points__c> result = new List<Discussion_Points__c>();
        for(Discussion_Points__c dp : TripRepPoints)
        {
            if((dp.Category__c == '' || dp.Category__c == null) && dp.internal_use_only__c == 'No')
            {
                result.add(dp);
            }
        }
        if(result.size() > 0)
            return result;
        else
            return null;
    }
    public List <Discussion_Points__c> getCurrentBusinessReview()
    {
        List<Discussion_Points__c> result = new List<Discussion_Points__c>();
        for(Discussion_Points__c dp : TripRepPoints)
        {
            if(dp.Category__c == 'Current Business Review' && dp.internal_use_only__c == 'No')
            {
                result.add(dp);
            }
        }
        if(result.size() > 0)
            return result;
        else
            return null;
    }
    public List <Discussion_Points__c> getNewBusinessOpportunity()
    {
        List<Discussion_Points__c> result = new List<Discussion_Points__c>();
        for(Discussion_Points__c dp : TripRepPoints)
        {
            if(dp.Category__c == 'New Business Opportunity' && dp.internal_use_only__c == 'No')
            {
                result.add(dp);
            }
        }
        if(result.size() > 0)
            return result;
        else
            return null;
    }
    public List <Discussion_Points__c> getCompetitiveIntelligence()
    {
        List<Discussion_Points__c> result = new List<Discussion_Points__c>();
        for(Discussion_Points__c dp : TripRepPoints)
        {
            if(dp.Category__c == 'Competitive Intelligence' && dp.internal_use_only__c == 'No')
            {
                result.add(dp);
            }
        }
        if(result.size() > 0)
            return result;
        else
            return null;
    }
    public List <Discussion_Points__c> getMiscellaneous()
    {
        List<Discussion_Points__c> result = new List<Discussion_Points__c>();
        for(Discussion_Points__c dp : TripRepPoints)
        {
            if(dp.Category__c == 'Miscellaneous' && dp.internal_use_only__c == 'No')
            {
                result.add(dp);
            }
        }
        if(result.size() > 0)
            return result;
        else
            return null;
    }
    public List <Discussion_Points__c> getActionItem()
    {
        List<Discussion_Points__c> result = new List<Discussion_Points__c>();
        for(Discussion_Points__c dp : TripRepPoints)
        {
            if(dp.Category__c == 'Action Item' && dp.internal_use_only__c == 'No')
            {
                result.add(dp);
            }
        }
        if(result.size() > 0)
            return result;
        else
            return null;
    }
        
    public void PointAddRow()
    {
        decimal no = 0;
        if(TripRepPoints.size() >= 1)
            no = TripRepPoints[TripRepPoints.size()-1].No__c+1;
        Discussion_Points__c newPoint = new Discussion_Points__c(Trip_Report__c = TripRep.id, No__c = no, Responsible_Selection__c = 'User', internal_use_only__c = 'Yes', Name = 'Point ' + (no + 1));
        TripRepPoints.add(newPoint);
        /* return null; */
        this.Pointsave(); 
    }
    public PageReference Pointsave()
    {
        try
        {
            upsert TripRepPoints;
            // ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Info, 'Successfully upserted '+TripRepPoints.size()+' lines.'));
        }
        catch (Exception e)
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.Error, 'Following exception occurred: ' + e.getMessage()));
        } 
        return null; 
    }   
    
    public PageReference PointDelete()
    {
        system.debug('selectPoint: '+selectPoint+'\n TripReports'+TripRepPoints);
        if(TripRepPoints.size() == 0)
            return null;
        else
        {
            Discussion_Points__c toBeDeleted = null;
            integer i = 0;
            for(Discussion_Points__c tpc : TripRepPoints)
            {
                if(tpc.No__c == selectPoint)
                {
                    if(tpc.id != null)
                        toBeDeleted = tpc;
                    TripRepPoints.remove(i); 
                    system.debug(toBeDeleted);                  
                    break;
                }
                i++;
            }
            if(toBeDeleted != null)
            {
                Delete toBeDeleted;
            }
        }
        return null; 
    }
}