objects/Opportunity_Task__c.object
<CustomObject>
    <description>Optional or mandatory tasks associated with opportunities.</description>
    <fields>
        <fullName>Assigned_User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Optional sales force user asked to complete this task</description>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Opportunity_Tasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Create_Event__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Create Task to Involved Users</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date_Required__c</fullName>
        <description>Date Required</description>
        <label>Date Required</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <description>Opportunity to which this task relates</description>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunity Tasks</relationshipLabel>
        <relationshipName>Opportunity_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity Task</label>
    <nameField>
        <displayFormat>Task-{000000}</displayFormat>
        <label>Opportunity Task Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/OppTaskAlertTestClass.cls
@isTest (SeeAlldata=true)
private class OppTaskAlertTestClass {

    static testMethod void TestOpptaskAlertTrig() {

Opportunity_Task__c b = new Opportunity_Task__c (Opportunity__c='0062000000Tty8xAAB',
RecordTypeId='01220000000UajYAAS',
Assigned_User__c='00520000003ApDiAAK' ,Date_Required__c=System.Today(),   Create_Event__c=TRUE);
    System.debug('Price before inserting new book: ' );
// Insert book
    insert b;

}
}