objects/User.object
<CustomObject>
    <fields>
        <fullName>MDM_External_Id__c</fullName>
        <defaultValue>&quot;&quot;</defaultValue>
        <description>Used to match users on upsert during deployment stage</description>
        <externalId>true</externalId>
        <label>MDM External Id</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>ResetUser__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Reset User</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

classes/TestResetPassword.cls
@isTest 
private class TestResetPassword  {
    static testMethod void TestResetPassword() 
{
 User  Usr = new User(LastName ='abc',ProfileId='00e20000001G1ChAAK', Email='sampath@kumar.com',MDM_External_Id__c='sampath@kumar.com', UserName ='sampath@kumar.com',Alias ='SampK11',TimeZoneSidKey ='Europe/London', LocaleSidKey ='en_GB'   ,EmailEncodingKey ='ISO-8859-1',   LanguageLocaleKey='en_US');
    insert Usr ;
    Usr.ResetUser__c=901;
Update Usr;
    }
    
}